### PR TITLE
Add mummy music file

### PR DESCRIPTION
**Pull request by criv5**
IT WILL BE DELETED LATER DONT CRY KASTLE PLEASE

### CODE REVIEW

**Comment by Kas-tle** [comment]
How are the commits so chaotic?

**Comment by Eboymc** [comment]
?????????????????

**Comment by criv5** [comment]
i couldnt figure out how to make a new folder without making a temp file

**Comment by Kas-tle** [comment]
If you don't update the pack.mcmeta it won't deploy

**Pull request merged**
